"""Pydantic mirror of the shared canvas + command contract.

Keep these models in sync with `frontend/src/schema` (the TypeScript source
of truth). Field names use the same camelCase as the JSON wire format.
"""

from .canvas import (
    CanvasEdge,
    CanvasGroup,
    CanvasMeta,
    CanvasNode,
    CanvasState,
    LineType,
    PipeData,
    Position,
    empty_canvas,
)
from .commands import (
    AddGroupCommand,
    AddNodeCommand,
    BatchCommand,
    CanvasCommand,
    ClearCommand,
    CommandMessage,
    CommandSource,
    ConnectCommand,
    DisconnectCommand,
    MoveNodeCommand,
    RemoveGroupCommand,
    RemoveNodeCommand,
    SelectCommand,
    ServerMessage,
    SnapshotMessage,
    UpdateEdgeCommand,
    UpdateGroupCommand,
    UpdateNodeCommand,
    command_adapter,
)
from .equipment import (
    EQUIPMENT_METADATA,
    EQUIPMENT_TYPES,
    EquipmentMeta,
    EquipmentType,
    PortDef,
)

__all__ = [
    "EQUIPMENT_METADATA",
    "EQUIPMENT_TYPES",
    "AddGroupCommand",
    "AddNodeCommand",
    "BatchCommand",
    "CanvasCommand",
    "CanvasEdge",
    "CanvasGroup",
    "CanvasMeta",
    "CanvasNode",
    "CanvasState",
    "ClearCommand",
    "CommandMessage",
    "CommandSource",
    "ConnectCommand",
    "DisconnectCommand",
    "EquipmentMeta",
    "EquipmentType",
    "LineType",
    "MoveNodeCommand",
    "PipeData",
    "PortDef",
    "Position",
    "RemoveGroupCommand",
    "RemoveNodeCommand",
    "SelectCommand",
    "ServerMessage",
    "SnapshotMessage",
    "UpdateEdgeCommand",
    "UpdateGroupCommand",
    "UpdateNodeCommand",
    "command_adapter",
    "empty_canvas",
]
